import requests

base='https://roamify-f9v5.onrender.com'
endpoints=[
 ('GET','/health',None),
 ('GET','/swagger',None),
 ('GET','/swagger/index.html',None),
 ('POST','/api/v1/auth/register',{'name':'test','email':'test@example.com','password':'password'}),
 ('POST','/api/v1/auth/login',{'email':'test@example.com','password':'password'}),
 ('POST','/api/v1/auth/social',{'provider':'facebook','token':'token'}),
 ('GET','/api/v1/users/search',None),
 ('GET','/api/v1/users/me',None),
 ('PATCH','/api/v1/users/me',{'bio':'x'}),
 ('GET','/api/v1/users/me/vibe',None),
 ('PUT','/api/v1/users/me/vibe',{'mood':'adventure'}),
 ('GET','/api/v1/users/me/privacy',None),
 ('PATCH','/api/v1/users/me/privacy',{'publicProfile':True}),
 ('POST','/api/v1/users/follow',{'userId':1}),
 ('DELETE','/api/v1/users/follow/1',None),
 ('GET','/api/v1/users/1',None),
 ('GET','/api/v1/users/1/followers',None),
 ('GET','/api/v1/users/1/following',None),
 ('POST','/api/v1/trips/plan-and-create',{'name':'t'}),
 ('POST','/api/v1/trips/',{'name':'t'}),
 ('GET','/api/v1/trips/',None),
 ('GET','/api/v1/trips/1',None),
 ('PATCH','/api/v1/trips/1',{'name':'t2'}),
 ('DELETE','/api/v1/trips/1',None),
 ('POST','/api/v1/trips/1/members',{'userId':1}),
 ('GET','/api/v1/trips/1/members',None),
 ('PATCH','/api/v1/trips/1/members/status',{'status':'accepted'}),
 ('DELETE','/api/v1/trips/1/members/1',None),
 ('POST','/api/v1/trips/1/itinerary',{'name':'it1'}),
 ('POST','/api/v1/trips/1/itinerary/generate-ai',{'days':3}),
 ('GET','/api/v1/trips/1/itinerary',None),
 ('PATCH','/api/v1/trips/1/itinerary/1',{'name':'it1b'}),
 ('DELETE','/api/v1/trips/1/itinerary/1',None),
 ('POST','/api/v1/trips/1/expenses',{'amount':10}),
 ('GET','/api/v1/trips/1/expenses',None),
 ('PATCH','/api/v1/trips/1/expenses/1',{'amount':15}),
 ('DELETE','/api/v1/trips/1/expenses/1',None),
 ('GET','/api/v1/trips/1/chat',None),
 ('POST','/api/v1/trips/1/chat',{'message':'hi'}),
 ('GET','/api/v1/trips/1/map',None),
 ('POST','/api/v1/posts/',{'title':'p'}),
 ('GET','/api/v1/posts/',None),
 ('GET','/api/v1/posts/1',None),
 ('PATCH','/api/v1/posts/1',{'title':'p2'}),
 ('DELETE','/api/v1/posts/1',None),
 ('POST','/api/v1/posts/1/like',None),
 ('DELETE','/api/v1/posts/1/like',None),
 ('GET','/api/v1/users/1/posts',None),
 ('POST','/api/v1/wishlist/items',{'name':'x'}),
 ('GET','/api/v1/wishlist/items',None),
 ('PATCH','/api/v1/wishlist/items/1',{'name':'x2'}),
 ('DELETE','/api/v1/wishlist/items/1',None),
 ('POST','/api/v1/wishlist/collections',{'name':'c'}),
 ('GET','/api/v1/wishlist/collections',None),
 ('GET','/api/v1/wishlist/collections/1',None),
 ('PATCH','/api/v1/wishlist/collections/1',{'name':'c2'}),
 ('DELETE','/api/v1/wishlist/collections/1',None),
 ('POST','/api/v1/wishlist/collections/1/items',{'itemId':1}),
 ('DELETE','/api/v1/wishlist/collections/1/items/1',None),
 ('GET','/api/v1/notifications/settings',None),
 ('PATCH','/api/v1/notifications/settings',{'email':True}),
 ('GET','/api/v1/notifications',None),
 ('GET','/api/v1/notifications/unread-count',None),
 ('PATCH','/api/v1/notifications/read-all',None),
 ('PATCH','/api/v1/notifications/1/read',None),
 ('GET','/api/v1/challenges/',None),
 ('GET','/api/v1/challenges/leaderboard',None),
 ('POST','/api/v1/challenges/',{'title':'c'}),
 ('POST','/api/v1/challenges/accept',{'challengeId':1}),
 ('POST','/api/v1/challenges/complete',{'challengeId':1}),
 ('GET','/api/v1/challenges/my-progress',None),
 ('GET','/api/v1/challenges/trivia',None),
 ('POST','/api/v1/challenges/trivia',{'question':'q'}),
 ('POST','/api/v1/challenges/trivia/answer',{'questionId':1,'answer':'a'}),
 ('PUT','/api/v1/passport/vault',{'country':'x'}),
 ('GET','/api/v1/passport/vault',None),
 ('DELETE','/api/v1/passport/vault',None),
 ('POST','/api/v1/passport/stamps',{'location':'x'}),
 ('GET','/api/v1/passport/stamps',None),
 ('DELETE','/api/v1/passport/stamps/1',None),
 ('GET','/api/v1/discovery/home',None),
 ('GET','/api/v1/discovery/vibe-search',None),
 ('GET','/api/v1/discovery/atlas',None),
 ('GET','/api/v1/discovery/atlas/geojson',None),
 ('GET','/api/v1/discovery/atlas/1',None),
 ('GET','/api/v1/discovery/price-drops',None),
 ('GET','/api/v1/discovery/recommended',None),
 ('POST','/api/v1/discovery/locations/generate',{'answers':['x']}),
 ('GET','/api/v1/search/global',None),
 ('GET','/api/v1/search/results',None),
 ('POST','/api/v1/assistant/travel',{'prompt':'where to go'})
]

print('started')
for method,path,payload in endpoints:
    url = base + path
    try:
        if method in ('GET','DELETE'):
            r = requests.request(method,url,timeout=15)
        else:
            r = requests.request(method,url,json=payload or {},timeout=15)
        text = ' '.join(str(r.text).split())[:220]
        print(f"{method} {path} -> {r.status_code} {text}")
    except Exception as e:
        print(f"{method} {path} -> ERROR {e}")
